### ISSUE TITLE
SQLite database model for entries of the shopping list

### ISSUE THREAD

**Issue by c0deful** [c0deful/shopping-list-app#2]
Each entry consists of:
* product name
* product price (optional)
* product count (defaults to 1)
* purchased flag (defaults to false)

**Comment by c0deful** [comment]
Thank you for expressing your interest, but this is a course assignment
that I need to do by myself. I will update the README soon to reflect this.

**Comment by govi20** [comment]
Oh okay. Also, don't use **good first issue** because people will end up filtering your issue. 
Cheers!
